#:schema node_modules/wrangler/config-schema.json
name = "nodejs-cf-worker-test-pm-two"
main = "src/index.ts"
compatibility_date = "2024-05-12"

# Automatically place your workloads in an optimal location to minimize latency.
# If you are running back-end logic in a Worker, running it closer to your back-end infrastructure
# rather than the end user may result in better performance.
# Docs: https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
[placement]
mode = "smart"

# Note: Use secrets to store sensitive data, like your API Key.
# Create a `.dev.vars` file in the root directory, and add: `API_KEY={your api key}`
# - https://developers.cloudflare.com/workers/configuration/secrets/

# Replace this with your subgraph endpoint
[vars]
SUBGRAPH_ENDPOINT = "https://gateway-arbitrum.network.thegraph.com/api/1df9c80e7e918f669b56b6097dd43f3e/subgraphs/id/66y54JQq5nSUPwruySqFPBM3FumChgcweEsFu2R9G12Y"

[[unsafe.bindings]]
name = "MY_RATE_LIMITER"
type = "ratelimit"
# An identifier you define, that is unique to your Cloudflare account.
# Must be an integer.
namespace_id = "123456123456156" #change this everytime u deploy a new worker

# Limit: the number of tokens allowed within a given period in a single
# Cloudflare location
# Period: the duration of the period, in seconds. Must be either 10 or 60
simple = { limit = 1, period = 10 }